[pr_update_changelog]
extra_instructions="""
    The current date is unimportant for the output. Do not use the current date.

    Instead, make a recommendation to the user based on this example:

    ### Added
    ...
    ### Changed
    ...
    ### Fixed
    ...
"""
