[tool.poetry]
name = "neo4j-genai"
version = "0.1.2"
description = "Python package to allow easy integration to Neo4j's GenAI features"
authors = ["Neo4j, Inc <team-gen-ai@neo4j.com>"]
license = "Apache License, Version 2.0"
readme = "README.md"

[[tool.poetry.packages]]
include = "neo4j_genai"
from = "src"

[tool.poetry.dependencies]
python = "^3.8.1"
neo4j = "^5.17.0"
types-requests = "^2.31.0.20240218"
pydantic = "^2.6.3"

[tool.poetry.group.dev.dependencies]
pylint = "^3.1.0"
mypy = "^1.8.0"
pytest = "^8.0.2"
pytest-mock = "^3.12.0"
pre-commit = { version = "^3.6.2", python = "^3.9" }
coverage = "^7.4.3"
ruff = "^0.3.0"
langchain-openai = "^0.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "",
]

[tool.coverage.paths]
source = ["src"]

[tool.pylint."MESSAGES CONTROL"]
disable="C0114,C0115"
