[tool.poetry]
name = "neo4j-genai"
version = "0.1.0"
description = ""
authors = ["Neo4j, Inc <team-gen-ai@neo4j.com>"]
license = "Apache License, Version 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
neo4j = "^5.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

exclude = ["**/tests/"]